import Head from 'next/head'
//import Image from 'next/image'
import styles from '../styles/Home.module.css'

export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
      <title> &copy; Aaron Padilla &rarr; IT Expert &trade;</title>
        <meta httpEquiv="refresh" content="4;url=/Fullstack" />
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
        
      </Head>

    </div>
  )
}
